import type {Context,Config} from '@netlify/functions';
import {getStore,getDeployStore} from '@netlify/blobs';
import {createHash,randomUUID} from 'node:crypto';
import {publicURL} from '../../lib/network.mjs';
import {VERSION,parseListing,urlOf,identity,clean} from '../../lib/extract.mjs';
import {makeJob,scanStep,summarize,resumeJob} from '../../lib/scanner.mjs';

function json(value:any,status=200){return new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}})}
function workspace(req:Request){const token=req.headers.get('x-videoscope-workspace')||'';if(!/^[a-zA-Z0-9_-]{24,100}$/.test(token))throw new Error('Open VideoScope in a fresh tab to initialize your device workspace.');return createHash('sha256').update(token).digest('hex')}
function storage(context:Context){return context.deploy.context==='production'?getStore({name:'videoscope-v33',consistency:'strong'}):getDeployStore({name:'videoscope-v33',consistency:'strong'})}
async function body(req:Request){if(Number(req.headers.get('content-length')||0)>5_000_000)throw new Error('Request exceeds the 5 MB import limit.');const text=await req.text();if(text.length>5_000_000)throw new Error('Request exceeds the 5 MB import limit.');return JSON.parse(text||'{}')}
function publicJob(j:any){const {robots,queue,fingerprints,visited,...rest}=j;return {...rest,details_remaining:queue?.length||0,has_more:!!j.next_url}}
function safeImported(x:any){const url=urlOf(x.url,'https://invalid.example');if(!url||!x.title)return null;const item:any={id:identity(url),url,title:clean(x.title).slice(0,600),source:new URL(url).hostname,creator:clean(x.creator).slice(0,150)||null,thumbnail_url:urlOf(x.thumbnail_url||x.thumbnail,url),date_raw:clean(x.date_raw).slice(0,150)||null,published_at:typeof x.published_at==='string'&&Number.isFinite(Date.parse(x.published_at))?x.published_at:null,date_precision:['day','timestamp','approximate'].includes(x.date_precision)?x.date_precision:'unavailable',fetched_at:new Date().toISOString(),comments:[],tags:Array.isArray(x.tags)?x.tags.slice(0,40).map((s:any)=>clean(s).slice(0,120)):[],source_files:[],download_links:[],extracted_by:'user import'};for(const key of ['views','likes','rating','rating_best','rating_count','comments_count','duration_seconds'])item[key]=typeof x[key]==='number'&&Number.isFinite(x[key])&&x[key]>=0?x[key]:null;item.is_hd=x.is_hd===true?true:null;return item}

export default async(req:Request,context:Context)=>{
 const parts=new URL(req.url).pathname.replace(/^\/api\/?/,'').split('/').filter(Boolean);
 if(req.method==='GET'&&parts[0]==='config')return json({version:VERSION,hosted:true,workspace:'device-isolated',max_pages:1000,default_scan_mode:'all',max_records:5000,detail_batch:1});
 try{
  const prefix='w/'+workspace(req)+'/',store=storage(context),get=async(key:string)=>await store.get(prefix+key,{type:'json'}) as any,set=async(key:string,v:any)=>await store.setJSON(prefix+key,v);
  if(req.method==='GET'&&parts[0]==='collections'&&parts.length===1){const listed=await store.list({prefix:prefix+'summary/'}),values=await Promise.all(listed.blobs.slice(0,100).map(b=>store.get(b.key,{type:'json'})));return json(values.filter(Boolean).sort((a:any,b:any)=>b.updated_at.localeCompare(a.updated_at)))}
  async function saveCollection(c:any){await set('collection/'+c.id,c);const {items,...summary}=c;await set('summary/'+c.id,summary)}
  if(parts[0]==='collections'&&/^[a-f0-9-]{36}$/.test(parts[1]||'')){const c=await get('collection/'+parts[1]);if(!c)return json({detail:'Collection not found in this workspace.'},404);if(req.method==='GET')return json(c);if(req.method==='DELETE'){await store.delete(prefix+'collection/'+c.id);await store.delete(prefix+'summary/'+c.id);return json({ok:true})}}
  if(req.method==='POST'&&parts[0]==='scans'&&parts.length===1){const b=await body(req),u=publicURL(String(b.url||''));if(b.start_at_first!==false){u.searchParams.delete('page');u.pathname=u.pathname.replace(/\/page\/\d+\/?$/,'/')};const cid=randomUUID(),jid=randomUUID(),time=new Date().toISOString(),job={...makeJob(u.href,b.pages,b.enrich),id:jid,collection_id:cid},c={id:cid,input:u.href,label:u.hostname,item_count:0,items:[],pages:0,created_at:time,updated_at:time,job_id:jid,version:VERSION};await set('job/'+jid,job);await saveCollection(c);return json(publicJob(job),201)}
  if(parts[0]==='scans'&&/^[a-f0-9-]{36}$/.test(parts[1]||'')){const key='job/'+parts[1],j=await get(key);if(!j)return json({detail:'Scan not found in this workspace.'},404);if(req.method==='GET')return json(publicJob(j));if(req.method==='POST'&&parts[2]==='stop'){j.status='stopped';j.message='Scan paused. Collected results are preserved.';await set(key,j);return json(publicJob(j))}if(req.method==='POST'&&parts[2]==='resume'){resumeJob(j);await set(key,j);return json(publicJob(j))}if(req.method==='POST'&&parts[2]==='step'){const b=await body(req);if(b.revision!==undefined&&b.revision!==j.revision)return json(publicJob(j));const c=await get('collection/'+j.collection_id);if(!c)return json({detail:'Collection not found.'},404);const result=await scanStep(j,c);await saveCollection(result.c);await set(key,result.job);return json(publicJob(result.job))}}
  if(req.method==='POST'&&parts[0]==='import'){const b=await body(req),content=String(b.content||'');let source:any,label='Imported collection',items:any[],input=urlOf(b.url,'https://invalid.example')||'';try{source=JSON.parse(content);items=(Array.isArray(source)?source:source.items||[]).slice(0,5000).map(safeImported).filter(Boolean);label=clean(source.label)||label}catch{if(!input)throw new Error('A saved HTML page needs its original public URL.');const parsed=parseListing(content,input);items=parsed.items;label=parsed.title}if(!items.length)throw new Error('No valid video records were found in this file.');const time=new Date().toISOString(),c={id:randomUUID(),input,label,item_count:items.length,items,pages:0,created_at:time,updated_at:time,provider:'import',version:VERSION,coverage:'imported file',metadata_coverage:summarize({items})};await saveCollection(c);return json(c,201)}
  return json({detail:'API route not found.'},404);
 }catch(e:any){return json({detail:e.message||'Unable to complete this request.'},400)}
};
export const config:Config={path:'/api/*'};
