import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const ctx=vm.createContext({module:{exports:{}},URL,Intl,Date,Set});
vm.runInContext(readFileSync('src/core.js','utf8'),ctx);const vs=ctx.module.exports;
const items=[{id:'a',title:'Alpha',views:10,duration_seconds:90},{id:'b',title:'Beta',views:null},{id:'c',title:'Gamma',views:50,duration_seconds:600}];
test('startup scripts come after actual controls',()=>{const h=readFileSync('static/index.html','utf8');assert.ok(h.indexOf('<script>')>h.indexOf('id="themeButton"'));assert.ok(h.indexOf('<script>')>h.indexOf('</main>'));});
test('boot waits for DOM when necessary',()=>{assert.match(readFileSync('src/app.js','utf8'),/DOMContentLoaded/);});
test('missing views do not pass a minimum filter',()=>assert.equal(vs.filterItems(items,{minViews:0}).length,2));
test('most viewed puts missing counts last',()=>assert.equal(vs.sortItems(items,'views_desc').map(x=>x.id).join(','),'c,a,b'));
test('case-insensitive title search works',()=>assert.equal(vs.filterItems(items,{query:'ALPHA'})[0].id,'a'));
test('duration minimum is expressed in minutes',()=>assert.equal(vs.filterItems(items,{minDuration:2})[0].id,'c'));
test('bookmarks filter by id',()=>assert.equal(vs.filterItems(items,{savedOnly:true},new Set(['b']))[0].id,'b'));
test('javascript URLs are rejected',()=>assert.equal(vs.safeURL('javascript:alert(1)'),''));
test('URLs with passwords are rejected',()=>assert.equal(vs.safeURL('https://x:secret@example.com'),''));
test('markup is escaped',()=>assert.equal(vs.escapeHTML('<script>'),'&lt;script&gt;'));
test('CSV formulas are escaped',()=>assert.ok(vs.csvCell('=1+1').startsWith('"\'')));
test('timecodes format correctly',()=>assert.equal(vs.timecode(3661),'1:01:01'));
