import test from 'node:test';
import assert from 'node:assert/strict';
import {parseListing,parseDetail,parseFeed,feedURL,numberOf,durationOf,dateOf,urlOf,identity} from '../lib/extract.mjs';
import {publicAddress,publicURL,allowedByRobots} from '../lib/network.mjs';
import {makeJob,scanStep} from '../lib/scanner.mjs';
const base='https://example.com/user/creator/videos';
const card=(id,title='Original title')=>`<div id="video_${id}" class="col-sm-4 m-t-15"><div class="thumb-overlay"><a href="/video/${id}/slug" title="${title}"><img data-original="https://cdn.example.com/${id}.jpg" src="/placeholder.png" alt="${title}"><div class="hd-text-icon">HD</div><div class="duration">01:02:03</div></a></div><a href="/video/${id}/slug" title="${title}">${title}</a><div class="video-added">7 days ago</div><div class="video-views">12,345 views</div><div class="video-rating"><b>77%</b></div></div>`;
const navigation='<nav><li><a href="?language=en">EN</a></li><li><a href="/login">Login</a></li><li><a href="/user/creator/videos/favorites">Favorite Videos</a></li></nav><ul class="pager"><li><a href="#">More</a></li></ul>';
test('native source card preserves exact fields, not navigation',()=>{const p=parseListing(navigation+card(1,'日本語の原題'),base);assert.equal(p.items.length,1);const v=p.items[0];assert.equal(v.title,'日本語の原題');assert.equal(v.thumbnail_url,'https://cdn.example.com/1.jpg');assert.equal(v.views,12345);assert.equal(v.rating,77);assert.equal(v.rating_best,100);assert.equal(v.duration_seconds,3723);assert.equal(v.is_hd,true);assert.equal(v.date_raw,'7 days ago');assert.equal(v.date_precision,'approximate');assert.equal(p.next,null)});
test('nav-only page cannot produce fabricated video cards',()=>assert.equal(parseListing(navigation,base).items.length,0));
test('duplicate card ids are merged',()=>assert.equal(parseListing(card(1)+card(1),base).items.length,1));
test('video slug changes do not duplicate identity',()=>assert.equal(identity('https://example.com/video/1/a'),identity('https://example.com/video/1/b')));
test('true zero view count is preserved',()=>assert.equal(parseListing(card(1).replace('12,345','0'),base).items[0].views,0));
test('no-rating marker is not zero percent approval',()=>assert.equal(parseListing(card(1).replace('class="video-rating"','class="video-rating no-rating"'),base).items[0].rating,null));
test('source total and forward pagination',()=>{const h=card(1)+'Showing 1 to 18 of 72 videos.<ul class="pagination"><li><a href="?page=1">1</a></li><li><a href="?page=3">3</a></li><li><a href="?page=2">»</a></li></ul>';const p=parseListing(h,base);assert.equal(p.expected,72);assert.equal(p.next,base+'?page=2')});
test('previous pages and external pagination are ignored',()=>{const h=card(1)+'<div class="pagination"><a href="?page=1">«</a><a href="https://evil.example/user/creator/videos?page=3">3</a></div>';assert.equal(parseListing(h,base+'?page=2').next,null)});
test('search query is preserved between pages',()=>assert.equal(parseListing('<div class="pagination"><a href="?page=2">2</a></div>', 'https://example.com/search?search_query=abc').next,null));
test('JSON-LD interaction types do not mix views and likes',()=>{const data={'@type':'VideoObject',name:'Lecture',url:'https://example.com/watch/123',thumbnailUrl:['https://example.com/thumb.jpg'],duration:'PT1H2M3S',uploadDate:'2024-01-02',interactionStatistic:[{interactionType:'https://schema.org/LikeAction',userInteractionCount:0},{interactionType:'https://schema.org/WatchAction',userInteractionCount:300}],aggregateRating:{ratingValue:4,bestRating:5}};const v=parseListing('<script type="application/ld+json">'+JSON.stringify(data)+'</script>',base).items[0];assert.equal(v.views,300);assert.equal(v.likes,0);assert.equal(v.rating,4);assert.equal(v.duration_seconds,3723);assert.equal(v.published_at,'2024-01-02');assert.equal(v.date_precision,'day')});
test('ordinary archive articles are candidates, not invented videos',()=>{const r=parseListing('<article><h2><a href="/post-a">A post</a></h2><img src="/image.jpg"></article>',base);assert.equal(r.items.length,0);assert.equal(r.candidates.length,1)});
test('detail reader prefers exact metadata and ignores recommended cards',()=>{const v= parseDetail('<meta property="og:type" content="video"><meta property="og:title" content="Exact source title"><meta property="og:image" content="/poster.jpg"><meta property="video:duration" content="123.4"><meta property="article:published_time" content="2020-01-02T03:04:05Z">'+card(99), 'https://example.com/video/2/a',parseListing(card(2),base).items[0]);assert.equal(v.id,identity('https://example.com/video/2/a'));assert.equal(v.title,'Exact source title');assert.equal(v.views,12345);assert.equal(v.duration_seconds,123.4);assert.equal(v.published_at,'2020-01-02T03:04:05.000Z')});
test('a plain article is not verified as a video detail',()=>assert.equal(parseDetail('<h1>Plain article</h1>','https://example.com/a').is_video,false));
test('source download links remain links; scripts are not executed',()=>{const v=parseDetail('<video><source src="/movie.mp4" type="video/mp4"></video><a download href="/movie.mp4">Download original</a><script>throw new Error("not executed")</script>','https://example.com/v');assert.equal(v.source_files[0].url,'https://example.com/movie.mp4');assert.equal(v.download_links[0].url,'https://example.com/movie.mp4')});
test('relative dates stay explicitly approximate',()=>{const d=dateOf('7 days ago',new Date('2026-09-19T12:00:00Z'));assert.equal(d.published_at,'2026-09-12T12:00:00.000Z');assert.equal(d.date_precision,'approximate')});
test('empty values never become zero',()=>{assert.equal(numberOf(''),null);assert.equal(durationOf(''),null);assert.equal(dateOf('').published_at,null)});
test('counts and durations support original formats',()=>{assert.equal(numberOf('1.2K views'),1200);assert.equal(durationOf('51:37'),3097);assert.equal(durationOf('PT2M3.5S'),123.5)});
test('unsafe URLs rejected',()=>{for(const x of ['javascript:alert(1)','data:text/html,a','https://me:password@example.com',''])assert.equal(urlOf(x,base),null)});
test('private IPv4, IPv6 and mapped addresses are blocked',()=>{for(const x of ['127.0.0.1','10.0.0.1','169.254.169.254','100.64.0.1','::1','fc00::1','fe80::1','::ffff:127.0.0.1'])assert.equal(publicAddress(x),false,x);assert.equal(publicAddress('1.1.1.1'),true)});
test('private URLs and nonstandard ports are blocked',()=>{for(const x of ['http://127.1','http://[::ffff:127.0.0.1]/','https://localhost','https://example.com:8080'])assert.throws(()=>publicURL(x))});
test('source robots exclusions are respected',()=>{const rules={origin:'https://example.com',text:'User-agent: *\nDisallow: /private/\n'};assert.equal(allowedByRobots(rules,'https://example.com/private/a'),false);assert.equal(allowedByRobots(rules,base),true)});
test('scan walks forward once and matches source total',async()=>{let j=makeJob(base,25,false),c={items:[],input:base};const mock=async url=>({url,html:(url.includes('page=2')?card(2):card(1)+'<div class="pagination"><a href="?page=2">2</a></div>')+'Showing 1 to 1 of 2 videos'}),robots=async()=>({origin:'https://example.com',text:''});await scanStep(j,c,mock,robots);await scanStep(j,c,mock,robots);assert.equal(j.status,'complete');assert.equal(j.pages,2);assert.equal(c.items.length,2);assert.equal(j.coverage,'source count matched')});
test('hitting page limit is partial, not all videos found',async()=>{const j=makeJob(base,1,false),c={items:[]};await scanStep(j,c,async url=>({url,html:card(1)+'Showing 1 to 18 of 72 videos<div class="pagination"><a href="?page=2">2</a></div>'}),async()=>({origin:'https://example.com',text:''}));assert.equal(j.status,'partial');assert.equal(j.coverage,'page limit reached')});
test('failed sources do not become successful empty scans',async()=>{const j=makeJob(base,1,false),c={items:[]};await scanStep(j,c,async()=>{throw new Error('HTTP 403')},async()=>({origin:'https://example.com',text:''}));assert.equal(j.status,'failed');assert.equal(c.items.length,0)});

test('RSS video feed entries become verified collection records',()=>{
 const xml='<?xml version="1.0"?><rss><channel><title>Creator feed</title><item><title>Public Video A</title><link>https://example.com/post-a/</link><pubDate>Mon, 14 Sep 2026 13:11:00 +0000</pubDate><dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">creator</dc:creator><category>Tag A</category><description><![CDATA[<iframe src="about:blank"></iframe><p>Video post</p>]]></description></item></channel></rss>';
 const p=parseFeed(xml,'https://example.com/creator/feed/');assert.equal(p.items.length,1);assert.equal(p.items[0].title,'Public Video A');assert.equal(p.items[0].creator,'creator');assert.equal(p.items[0].published_at,'2026-09-14T13:11:00.000Z');assert.equal(p.items[0].date_precision,'timestamp');assert.equal(p.items[0].tags[0],'Tag A')
});
test('feed fallback URL stays on the same archive path',()=>assert.equal(feedURL('https://example.com/actress/name/'),'https://example.com/actress/name/feed/'));
test('blocked archive can fall back to a public RSS feed',async()=>{
 const url='https://example.com/actress/name/',j=makeJob(url,3,false),c={items:[],input:url};let calls=[];
 const read=async(target)=>{calls.push(target);if(target===url){const e=new Error('HTTP 403');e.status=403;throw e}return {url:target,contentType:'application/rss+xml',html:'<rss><channel><title>Name</title><item><title>Video A</title><link>https://example.com/a/</link><pubDate>Mon, 14 Sep 2026 13:11:00 +0000</pubDate><description><![CDATA[<iframe src="about:blank"></iframe> video]]></description></item></channel></rss>'}};
 await scanStep(j,c,read,async()=>({origin:'https://example.com',text:''}));assert.equal(c.items.length,1);assert.equal(c.items[0].title,'Video A');assert.ok(calls.includes('https://example.com/actress/name/feed/'))
});
