import * as cheerio from 'cheerio/slim';
import {createHash} from 'node:crypto';

export const VERSION='3.7.0';
export const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
export function urlOf(v,base){if(typeof v!=='string'||!v.trim()||/^(#|javascript:|data:|blob:|mailto:)/i.test(v.trim()))return null;try{const u=new URL(v,base);if(!/^https?:$/.test(u.protocol)||u.username||u.password)return null;u.hash='';return u.href}catch{return null}}
export function numberOf(v){if(v===null||v===undefined||v==='')return null;if(typeof v==='number')return Number.isFinite(v)&&v>=0?v:null;const m=clean(v).replace(/,/g,'').match(/(?:^|\s)(\d+(?:\.\d+)?)\s*([kmb]|万)?(?:\s|$|[^a-z0-9.])/i);if(!m)return null;return Number(m[1])*({k:1e3,m:1e6,b:1e9,'万':1e4}[m[2]?.toLowerCase()]||1)}
export function durationOf(v){if(typeof v==='number')return v>=0?v:null;const s=clean(v),iso=s.match(/^P(?:(\d+)D)?T(?:(\d+(?:\.\d+)?)H)?(?:(\d+(?:\.\d+)?)M)?(?:(\d+(?:\.\d+)?)S)?$/i);if(iso)return Number(iso[1]||0)*86400+Number(iso[2]||0)*3600+Number(iso[3]||0)*60+Number(iso[4]||0);const m=s.match(/(?:^|\s)(?:(\d+):)?(\d{1,2}):(\d{2})(?:\s|$)/);if(m)return Number(m[1]||0)*3600+Number(m[2])*60+Number(m[3]);return /^\d+(?:\.\d+)?$/.test(s)?Number(s):null}
export function dateOf(raw,at=new Date()){
 const text=clean(raw);if(!text)return {published_at:null,date_raw:null,date_precision:'unavailable'};
 const rel=text.match(/(\d+)\s*(second|minute|hour|day|week|month|year)s?\s+ago/i);if(rel){const unit=rel[2].toLowerCase(),ms={second:1000,minute:60000,hour:3600000,day:86400000,week:604800000,month:2629800000,year:31557600000}[unit];return {published_at:new Date(+at-Number(rel[1])*ms).toISOString(),date_raw:text,date_precision:'approximate'}}
 const iso=text.match(/\b\d{4}-\d{2}-\d{2}(?:[T ]\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?(?:Z|[+-]\d{2}:?\d{2})?)?/);
 const named=text.match(/\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s+\d{1,2},?\s+\d{4}/i);
 const val=iso?.[0]||named?.[0];if(val){const date=new Date(val);if(!Number.isNaN(+date)){const hasTime=val.includes(':');return {published_at:hasTime?date.toISOString():date.toISOString().slice(0,10),date_raw:text,date_precision:hasTime?'timestamp':'day'}}}
 if(/\b\d{4}\b/.test(text)){const parsed=new Date(text);if(!Number.isNaN(+parsed))return {published_at:parsed.toISOString(),date_raw:text,date_precision:/\d{1,2}:\d{2}/.test(text)?'timestamp':'day'}}
 return {published_at:null,date_raw:text,date_precision:'unavailable'};
}
export function identity(url){const u=new URL(url),id=u.pathname.match(/^\/video\/(\d+)(?:\/|$)/);return createHash('sha256').update(id?u.hostname.replace(/^www\./,'')+'/video/'+id[1]:u.href).digest('hex').slice(0,24)}
function baseItem(url,title,at){return {id:identity(url),url,title:clean(title),source:new URL(url).hostname.replace(/^www\./,''),creator:null,thumbnail_url:null,views:null,likes:null,dislikes:null,rating:null,rating_best:null,rating_count:null,comments_count:null,duration_seconds:null,published_at:null,date_raw:null,date_precision:'unavailable',is_hd:null,availability:'public listing',fetched_at:at.toISOString(),tags:[],comments:[],source_files:[],download_links:[],players:[],field_sources:{}}}
function thumb(root,base){const img=root.find('img').first();for(const attr of ['data-original','data-src','data-lazy-src','src']){const s=urlOf(img.attr(attr),base);if(s&&!/placeholder|blank\.(gif|png)|1x1/i.test(s))return s}const srcset=img.attr('data-srcset')||img.attr('srcset');return srcset?urlOf(srcset.split(',').at(-1).trim().split(/\s+/)[0],base):null}
function extractDate(root,at){const el=root.find('[itemprop="uploadDate"],time,[itemprop="datePublished"],.video-added,.video-date,.entry-date,.date').first();return dateOf(el.attr('content')||el.attr('datetime')||el.attr('title')||el.text(),at)}
function navigation(root){return !!root.closest('nav,header,footer,[role="navigation"],.pagination,.pager,.menu,.navbar,.breadcrumb').length}
function titleFrom(root,a){const titleAnchor=root.find('a[href]').filter((_,n)=>clean(root.constructor?root.find(n).text():'')).last();return clean(a.attr('title')||root.find('h2 a,h3 a,.video-title,.title,.entry-title').first().text()||root.children('a').last().attr('title')||root.children('a').last().text()||root.find('img').first().attr('alt')||a.text())}
function fields(root,base,at){const text=clean(root.text()),ratingNode=root.find('.video-rating,.rating,[itemprop="ratingValue"]').first();let rating=numberOf(ratingNode.attr('content')||ratingNode.text());if(ratingNode.hasClass('no-rating'))rating=null;const percent=/%/.test(ratingNode.text());const viewText=clean(root.find('.video-views,.views,[itemprop="interactionCount"],[data-views]').first().attr('data-views')||root.find('.video-views,.views,[itemprop="interactionCount"]').first().text());return {thumbnail_url:thumb(root,base),views:numberOf(viewText)||(/\b0\s+views?\b/i.test(viewText)?0:numberOf(text.match(/([\d,.]+\s*[kmb]?)\s+views?\b/i)?.[1])),likes:numberOf(root.find('.like-count,.likes-count,[data-likes]').first().attr('data-likes')||root.find('.like-count,.likes-count').first().text()),rating,rating_best:rating!==null?(percent?100:numberOf(root.find('[itemprop="bestRating"]').attr('content'))):null,rating_count:numberOf(root.find('[itemprop="ratingCount"],.rating-count').first().attr('content')||root.find('.rating-count').first().text()),duration_seconds:durationOf(root.find('.duration,.video-duration,.length,time.duration').first().text()),...extractDate(root,at),is_hd:root.find('.hd-text-icon,.is-hd,.hd').length?true:null,availability:root.find('.private-text-icon,.private-video,.locked').length?'private listing':'public listing'}}
export function jsonObjects($){const out=[];$('script[type="application/ld+json"]').each((_,n)=>{try{const stack=[JSON.parse($(n).text())];let guard=0;while(stack.length&&guard++<4000){const x=stack.pop();if(!x||typeof x!=='object')continue;if(Array.isArray(x)){stack.push(...x);continue}out.push(x);for(const v of Object.values(x))if(v&&typeof v==='object')stack.push(v)}}catch{}});return out}
function isVideo(x){return [].concat(x?.['@type']||[]).some(t=>String(t).split('/').at(-1)==='VideoObject')}
function directMedia(raw,base,type=''){
 const url=urlOf(raw,base);if(!url)return null;
 const path=new URL(url).pathname.toLowerCase(),mime=String(type||'').toLowerCase();
 if(!/\.(mp4|webm|ogv|ogg|m4v|mov)(?:$)/i.test(path)&&!/^video\/(mp4|webm|ogg|quicktime|x-m4v)/i.test(mime))return null;
 return {url,type:type||null,label:'Original media file'};
}
function uniqueLinks(list){const seen=new Set();return list.filter(x=>x?.url&&!seen.has(x.url)&&(seen.add(x.url),true))}

function schemaItem(x,base,at){const url=urlOf(x.url||x.mainEntityOfPage?.['@id']||x['@id']||base,base);if(!url||!x.name)return null;const v=baseItem(url,x.name,at);Object.assign(v,{creator:x.author?.name||x.creator?.name||null,thumbnail_url:urlOf([].concat(x.thumbnailUrl||x.thumbnail?.url||[])[0],base),description:clean(x.description).slice(0,12000),duration_seconds:durationOf(x.duration),...dateOf(x.uploadDate||x.datePublished,at),rating:numberOf(x.aggregateRating?.ratingValue),rating_best:numberOf(x.aggregateRating?.bestRating)??(x.aggregateRating?5:null),rating_count:numberOf(x.aggregateRating?.ratingCount||x.aggregateRating?.reviewCount),comments_count:numberOf(x.commentCount),extracted_by:'VideoObject',field_sources:{title:'VideoObject.name',published_at:'VideoObject.uploadDate/datePublished'}});const schemaFiles=[].concat(x.contentUrl||[]).map(raw=>directMedia(raw,base,x.encodingFormat)).filter(Boolean);v.source_files=uniqueLinks(schemaFiles);if(v.source_files.length)v.field_sources.source_files='VideoObject.contentUrl';for(const stat of [].concat(x.interactionStatistic||[])){const type=String(stat.interactionType?.['@type']||stat.interactionType||'');const field=/Watch|View/.test(type)?'views':/Dislike/.test(type)?'dislikes':/Like/.test(type)?'likes':/Comment/.test(type)?'comments_count':null;if(field)v[field]=numberOf(stat.userInteractionCount)}return v}
function collectionPath(url){return new URL(url).pathname.replace(/\/page\/\d+\/?$/,'/').replace(/\/$/,'')}
export function nextPage($,base){const current=new URL(base),currentPage=Number(current.searchParams.get('page')||current.pathname.match(/\/page\/(\d+)/)?.[1]||1),found=[];$('a[rel~="next"],.pagination a[href],.nav-links a[href],a.page-numbers,a.next').each((_,n)=>{const a=$(n),url=urlOf(a.attr('href'),base);if(!url)return;const u=new URL(url);if(u.origin!==current.origin||collectionPath(url)!==collectionPath(base)||url===base)return;if(a.closest('.disabled').length)return;for(const [k,v] of current.searchParams)if(k!=='page'&&!k.startsWith('utm_')&&u.searchParams.get(k)!==v)return;const p=Number(u.searchParams.get('page')||u.pathname.match(/\/page\/(\d+)/)?.[1]||0);const next=/next|[»›→]/i.test(a.text()+' '+(a.attr('rel')||'')+' '+(a.attr('aria-label')||''));if(p>currentPage)found.push({url,p});else if(next&&!p)found.push({url,p:currentPage+1})});return found.sort((a,b)=>a.p-b.p)[0]?.url||null}

export function wordpressPostURL(raw){
 const u=new URL(raw),slug=u.pathname.split('/').filter(Boolean).pop();if(!slug)return null;
 u.pathname='/wp-json/wp/v2/posts';u.search='';u.searchParams.set('slug',slug);u.searchParams.set('_embed','wp:featuredmedia');u.hash='';return u.href
}
export function parseWordPressPostMeta(json,base){
 let data;try{data=typeof json==='string'?JSON.parse(json):json}catch{return null}
 const post=Array.isArray(data)?data[0]:data;if(!post||typeof post!=='object')return null;
 const media=post?._embedded?.['wp:featuredmedia']?.[0]||null,sizes=media?.media_details?.sizes||{};
 const candidates=[sizes.large?.source_url,sizes.medium_large?.source_url,sizes.medium?.source_url,media?.source_url].map(x=>urlOf(x,base)).filter(Boolean);
 return {thumbnail_url:candidates[0]||null,post_id:post.id||null,featured_media:post.featured_media||null}
}

export function feedURL(raw){const u=new URL(raw);if(/\/feed\/?$/.test(u.pathname))return u.href;u.pathname=u.pathname.replace(/\/$/,'')+'/feed/';u.search='';u.hash='';return u.href}
export function parseFeed(xml,base,at=new Date()){
 const $=cheerio.load(xml,{xmlMode:true}),items=[];const nodes=$('item,entry');
 nodes.each((_,n)=>{const node=$(n),title=clean(node.find('title').first().text());let href=node.find('link').first().attr('href')||node.find('link').first().text()||node.find('guid').first().text(),url=urlOf(href,base);if(!title||!url)return;
  const raw=node.find('content\\:encoded').first().text()||node.find('content').first().text()||node.find('description').first().text()||node.find('summary').first().text(),h=cheerio.load(raw||'');
  const evidence=h('video,source,iframe,embed,object').length||/\bvideo\b/i.test(title)||/\bvideo\b/i.test(raw||'');if(!evidence)return;
  const v=baseItem(url,title,at);const direct=name=>node.children().filter((_,x)=>String(x.name||'').toLowerCase()===name).first();v.creator=clean(direct('dc:creator').text()||node.find('author name').first().text()||direct('author').text())||null;
  const image=node.find('media\\:thumbnail').first().attr('url')||node.find('media\\:content[type^="image/"]').first().attr('url')||h('img').first().attr('data-src')||h('img').first().attr('src');v.thumbnail_url=urlOf(image,base);
  const rawDate=clean(direct('pubdate').text()||direct('published').text()||direct('updated').text());Object.assign(v,dateOf(rawDate,at));
  v.tags=[...new Set(node.find('category').map((_,x)=>clean($(x).text()||$(x).attr('term'))).get().filter(Boolean))].slice(0,40);v.description=clean(h.text()).slice(0,12000)||null;const playerUrls=[];h('[onclick]').each((_,x)=>{const m=String(h(x).attr('onclick')||'').match(/playEmbed\(\s*["']([^"']+)/i);if(m)playerUrls.push(m[1])});h('iframe[src],iframe[data-src],embed[src]').each((_,x)=>playerUrls.push(h(x).attr('data-src')||h(x).attr('src')));v.players=[...new Set(playerUrls.map(x=>urlOf(x,base)).filter(x=>x&&!/^about:blank/i.test(x)))].slice(0,12).map((url,i)=>({url,label:'Player '+(i+1)}));const feedFiles=[];h('video[src],video source[src]').each((_,x)=>{const rec=directMedia(h(x).attr('src'),base,h(x).attr('type'));if(rec)feedFiles.push(rec)});node.find('enclosure[url],media\\:content[url]').each((_,x)=>{const rec=directMedia($(x).attr('url'),base,$(x).attr('type'));if(rec)feedFiles.push(rec)});v.source_files=uniqueLinks(feedFiles);v.download_links=uniqueLinks(h('a[download],a[rel~="download"],a[href]').map((_,x)=>{const href=h(x).attr('href'),rec=directMedia(href,base);if(!rec&&!h(x).is('[download],[rel~="download"]'))return null;const url=urlOf(href,base);return url?{url,label:clean(h(x).text()||h(x).attr('download'))||'Source download'}:null}).get().filter(Boolean));v.found_on=base;v.extracted_by='RSS/Atom video entry';v.field_sources={title:'feed title',published_at:'feed publication date',thumbnail_url:v.thumbnail_url?'feed/content image':null,players:v.players.length?'feed embed controls':null};items.push(v)
 });
 const u=new URL(base),page=Number(u.searchParams.get('paged')||u.searchParams.get('page')||1);let next=null;if(nodes.length>=10&&items.length){u.searchParams.set('paged',String(page+1));next=u.href}
 return {items,candidates:[],next,expected:null,title:clean($('channel > title').first().text()||$('feed > title').first().text()||new URL(base).hostname),kind:'feed-video-list',source_url:base};
}

export function parseListing(html,base,at=new Date()){
 const $=cheerio.load(html),items=new Map(),candidates=new Map();const add=x=>{if(x?.title&&x.url){const prev=items.get(x.id);items.set(x.id,prev?{...prev,...Object.fromEntries(Object.entries(x).filter(([,v])=>v!==null))}:x)}};
 const native=$('[id^="video_"]').filter((_,n)=>/^video_\d+$/.test($(n).attr('id')||''));
 native.each((_,n)=>{const root=$(n);if(navigation(root))return;const a=root.find('a[href]').filter((_,a)=>/^\/video\/\d+(?:\/|$)/.test(new URL(urlOf($(a).attr('href'),base)||base).pathname)).first();const url=urlOf(a.attr('href'),base);if(!url)return;const title=clean(a.attr('title')||root.children('a').last().text()||root.find('img').attr('alt'));const v={...baseItem(url,title,at),...fields(root,base,at),found_on:base,extracted_by:'native video card',field_sources:{title:'video link title',thumbnail_url:'video card image',views:'.video-views',rating:'.video-rating',published_at:'.video-added'}};const match=new URL(base).pathname.match(/^\/user\/([^/]+)\/videos/);if(match)v.creator=decodeURIComponent(match[1]);add(v)});
 for(const x of jsonObjects($).filter(isVideo))add(schemaItem(x,base,at));
 if(!native.length){$('.video-item,.video-card,.thumb-block,.clip-card,.list-videos .item,[itemtype$="/VideoObject"],article,.well.well-sm:has(.video-title)').each((_,n)=>{const root=$(n);if(navigation(root))return;const a=root.find('h2 a[href],h3 a[href],a.title[href],a[href]').first(),url=urlOf(a.attr('href'),base);if(!url||url===base)return;const path=new URL(url).pathname;if(/\/(?:login|signup|register|user|category|tag|search)\/?$/i.test(path))return;const title=clean(a.attr('title')||root.find('h2,h3,.title,.video-title,.entry-title').first().text()||root.find('img').attr('alt')||a.text());if(!title||/^(en|login|more|favorite videos|next|previous)$/i.test(title))return;const v={...baseItem(url,title,at),...fields(root,base,at),found_on:base,extracted_by:'semantic video card'};const evidence=root.find('video,[itemtype$="/VideoObject"]').length||/\/(?:video|watch|videos|clip|movie)\/[^/]+/.test(path)||v.duration_seconds!==null||/video/i.test(root.attr('class')||'');if(evidence)add(v);else if(n.tagName==='article'&&v.thumbnail_url)candidates.set(v.id,v)})}
 const text=clean($('body').length?$('body').text():$.root().text()),count=text.match(/Showing\s+[\d,]+\s+to\s+[\d,]+\s+of\s+([\d,]+)\s+videos/i);return {items:[...items.values()],candidates:[...candidates.values()],next:nextPage($,base),expected:count?Number(count[1].replace(/,/g,'')):null,title:clean($('h1').first().text()||$('title').text()||new URL(base).hostname),kind:native.length?'native-video-list':items.size?'video-list':candidates.size?'archive-candidates':'unrecognized',source_url:base};
}
export function parseDetail(html,base,existing=null,at=new Date()){
 const $=cheerio.load(html),meta=name=>$('meta[property="'+name+'"],meta[name="'+name+'"]').first().attr('content'),objects=jsonObjects($),schema=objects.find(isVideo),ogType=meta('og:type')||'',hasVideo=!!schema||/^video/.test(ogType)||!!$('video').length||!!$('iframe[src*="youtube.com/embed"],iframe[src*="player.vimeo.com/video"],iframe[src*="/embed/"]').length;
 const title=meta('og:title')||$('h1').first().text()||schema?.name||existing?.title;const item={...(existing||baseItem(base,title,at))};if(!hasVideo)return {...item,detail_status:'no public video metadata',is_video:false};
 if(schema){const parsed=schemaItem(schema,base,at);if(parsed)for(const [k,v]of Object.entries(parsed))if(v!==null&&v!==''&&!(Array.isArray(v)&&!v.length))item[k]=v}
 item.id=existing?.id||identity(base);item.url=existing?.url||base;item.title=clean(title)||item.title;item.is_video=true;item.detail_status='read';item.detail_fetched_at=at.toISOString();item.thumbnail_url=urlOf(meta('og:image')||$('video').attr('poster'),base)||item.thumbnail_url;item.description=clean(meta('og:description')||$('.video-description,.entry-content').first().text()).slice(0,12000)||item.description||null;item.duration_seconds=durationOf(meta('video:duration'))??item.duration_seconds;
 const raw=meta('video:release_date')||meta('article:published_time')||$('[itemprop="uploadDate"],[itemprop="datePublished"]').first().attr('content')||$('time').first().attr('datetime');if(raw){const dt=dateOf(raw,at);if(dt.published_at)Object.assign(item,dt)}
 item.tags=[...new Set($('meta[property="video:tag"]').map((_,n)=>clean($(n).attr('content'))).get().concat(schema?.keywords?[].concat(schema.keywords).flatMap(v=>String(v).split(',')):[]))].filter(Boolean).slice(0,40);
 const scoped=$('.video-details,.video-info,#video-info,#videoInfo,#video_details,.video-actions').first();if(scoped.length){const txt=clean(scoped.text());for(const [field,rx]of [['views',/([\d,]+)\s+views?/i],['likes',/([\d,]+)\s+likes?/i],['comments_count',/([\d,]+)\s+comments?/i]]){const m=txt.match(rx);if(m)item[field]=numberOf(m[1])}}
 const comments=[];$('.comment-body,[id^="comment_"]').each((_,n)=>{const r=$(n),body=clean(r.find('.comment-text,.comment-content,.media-body p').first().text());if(body)comments.push({text:body.slice(0,2000),author:clean(r.find('.comment-author,.author,cite').first().text())||null,date_raw:clean(r.find('time').text())||null})});item.comments=comments.slice(0,30);item.comments_status=comments.length?'public comments present':'No comment text was exposed in the returned page';
 const explicitDownloads=$('a[download],a[rel~="download"],a[href]').map((_,n)=>{const a=$(n),href=a.attr('href'),media=directMedia(href,base);if(!media&&!a.is('[download],[rel~="download"]'))return null;const url=urlOf(href,base);return url?{url,label:clean(a.text()||a.attr('download'))||'Source download'}:null}).get().filter(Boolean);
 const directFiles=$('video source[src],video[src]').map((_,n)=>directMedia($(n).attr('src'),base,$(n).attr('type'))).get().filter(Boolean);const ogFiles=[meta('og:video:secure_url'),meta('og:video:url'),meta('og:video')].map(raw=>directMedia(raw,base,meta('og:video:type'))).filter(Boolean);const schemaFiles=schema?[].concat(schema.contentUrl||[]).map(raw=>directMedia(raw,base,schema.encodingFormat)).filter(Boolean):[];item.source_files=uniqueLinks([...directFiles,...ogFiles,...schemaFiles]).slice(0,12);item.download_links=uniqueLinks(explicitDownloads).slice(0,12);
 item.players=[...new Set($('iframe[src],iframe[data-src],embed[src]').map((_,n)=>urlOf($(n).attr('data-src')||$(n).attr('src'),base)).get().filter(x=>x&&!/^about:blank/i.test(x)))].slice(0,12).map((url,i)=>({url,label:'Player '+(i+1)}));
 item.field_sources={...item.field_sources,title:meta('og:title')?'detail og:title':item.field_sources?.title,thumbnail_url:meta('og:image')?'detail og:image':item.field_sources?.thumbnail_url};return item;
}
