import http from 'node:http';
import https from 'node:https';
import dns from 'node:dns/promises';
import {gunzipSync,inflateSync,brotliDecompressSync} from 'node:zlib';
import ipaddr from 'ipaddr.js';
import robotsParser from 'robots-parser';

export function publicAddress(address){try{return ipaddr.process(address).range()==='unicast'}catch{return false}}
export function publicURL(raw){let u;try{u=new URL(raw)}catch{throw new Error('Enter a complete public website URL.')}if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.href.length>4096)throw new Error('Only public HTTP or HTTPS page addresses are supported.');if(u.port&&!['80','443'].includes(u.port))throw new Error('Only standard website ports are supported.');const h=u.hostname.replace(/^\[|\]$/g,'').toLowerCase();if(h==='localhost'||h.endsWith('.local')||h.endsWith('.internal')||h.endsWith('.localhost')||h==='metadata.google.internal'||(ipaddr.isValid(h)&&!publicAddress(h)))throw new Error('Private network addresses cannot be scanned.');u.hash='';return u}
async function addresses(host){let timer;try{return await Promise.race([dns.lookup(host,{all:true,verbatim:false}),new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('Source DNS lookup timed out.')),5000)})])}finally{clearTimeout(timer)}}
async function requestOnce(u,limit,timeout){const h=u.hostname.replace(/^\[|\]$/g,''),all=await addresses(h);if(!all.length||all.some(x=>!publicAddress(x.address)))throw new Error('Source address is not a public network address.');const chosen=all.find(x=>x.family===4)||all[0];return await new Promise((resolve,reject)=>{let settled=false;const finish=(err,data)=>{if(settled)return;settled=true;clearTimeout(timer);err?reject(err):resolve(data)};const req=(u.protocol==='https:'?https:http).request(u,{method:'GET',family:chosen.family,autoSelectFamily:false,lookup:(_host,options,cb)=>options?.all?cb(null,[chosen]):cb(null,chosen.address,chosen.family),headers:{'user-agent':'VideoScope/3.3 (public metadata reader)','accept':'text/html,application/xhtml+xml,text/plain;q=0.5','accept-language':'en-US,en;q=0.8','accept-encoding':'gzip, deflate, br'}},res=>{const chunks=[];let size=0;res.on('data',chunk=>{size+=chunk.length;if(size>limit){req.destroy(new Error('The returned page exceeded the 4 MB safety limit.'));return}chunks.push(chunk)});res.on('error',e=>finish(e));res.on('end',()=>{try{let bytes=Buffer.concat(chunks),enc=res.headers['content-encoding'];if(enc==='gzip')bytes=gunzipSync(bytes,{maxOutputLength:limit});if(enc==='deflate')bytes=inflateSync(bytes,{maxOutputLength:limit});if(enc==='br')bytes=brotliDecompressSync(bytes,{maxOutputLength:limit});if(bytes.length>limit)throw new Error('The expanded page exceeded the 4 MB safety limit.');const charset=String(res.headers['content-type']||'').match(/charset\s*=\s*["']?([^;"'\s]+)/i)?.[1]||'utf-8';let text;try{text=new TextDecoder(charset).decode(bytes)}catch{text=bytes.toString('utf8')}finish(null,{status:res.statusCode,headers:res.headers,text})}catch(e){finish(e)}})});const timer=setTimeout(()=>req.destroy(new Error('The source took too long to return its page.')),timeout);req.on('error',e=>finish(e));req.end()})}
export async function readPublic(raw,{html=true,limit=4_000_000,timeout=15000}={}){let u=publicURL(raw);for(let hop=0;hop<5;hop++){const r=await requestOnce(u,limit,timeout);if([301,302,303,307,308].includes(r.status)){if(!r.headers.location)throw new Error('The source supplied an empty redirect.');u=publicURL(new URL(r.headers.location,u).href);continue}if(r.status<200||r.status>=300){const e=new Error(r.status===403?'The source refused this server request (HTTP 403). No access controls were bypassed.':r.status===429?'The source asked us to slow down (HTTP 429). Try again later.':'The source returned HTTP '+r.status+'.');e.status=r.status;throw e}if(html&&!/text\/html|application\/xhtml/i.test(r.headers['content-type']||''))throw new Error('That address does not return a web page.');return {url:u.href,html:r.text,contentType:r.headers['content-type'],status:r.status}}throw new Error('Too many source redirects.')}
export async function readRobots(raw){const origin=publicURL(raw).origin,url=origin+'/robots.txt';try{const result=await readPublic(url,{html:false,limit:150000,timeout:5000});return {origin,text:result.html}}catch(e){return {origin,text:'',warning:e.status===404?null:'Source crawl instructions could not be retrieved.'}}}
export function allowedByRobots(rules,url){if(!rules?.text)return true;return robotsParser(rules.origin+'/robots.txt',rules.text).isAllowed(url,'VideoScope')!==false}
