import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';
const site=process.env.SITE_URL||'https://deploy-preview-1--videoscope-3-tahmid.netlify.app',token=randomUUID().replace(/-/g,''),headers={'content-type':'application/json','x-videoscope-workspace':token};
async function call(path,b,otherToken){const r=await fetch(site+path,{method:b===undefined?'GET':'POST',headers:{...headers,...(otherToken?{'x-videoscope-workspace':otherToken}:{})},body:b===undefined?undefined:JSON.stringify(b),signal:AbortSignal.timeout(55000)});const text=await r.text();let x;try{x=JSON.parse(text)}catch{throw new Error('Non-JSON response '+r.status+' from '+path)}if(!r.ok)throw new Error(path+': '+(x.detail||r.status));return x}
let ready=false;for(let i=0;i<20;i++){try{const config=await call('/api/config');if(config.version==='3.3.0'){ready=true;break}}catch{}await new Promise(r=>setTimeout(r,6000))}assert.ok(ready,'Expected hosted scanner version did not become ready');
assert.deepEqual(await call('/api/collections'),[]);
const source='https://www.tokyomotion.net/user/yua_xx/videos';let job=await call('/api/scans',{url:source,pages:25,enrich:true});let steps=0;
while(!['complete','partial','failed'].includes(job.status)&&steps++<100){job=await call('/api/scans/'+job.id+'/step',{revision:job.revision});console.log('HOSTED_SCAN',JSON.stringify({status:job.status,stage:job.stage,pages:job.pages,items:job.items,expected:job.expected,details_checked:job.details_checked,message:job.message}));}
assert.equal(job.status,'complete',job.message);assert.ok(job.items>0);assert.equal(job.items,job.expected);const c=await call('/api/collections/'+job.collection_id);assert.equal(c.items.length,job.expected);assert.equal(new Set(c.items.map(x=>x.id)).size,c.items.length);
for(const x of c.items){assert.ok(x.title&&!/^(EN|Login|More|Favorite Videos)$/.test(x.title),'Navigation appeared as video');assert.ok(x.thumbnail_url);assert.equal(typeof x.views,'number');assert.ok(x.duration_seconds>0);assert.ok(x.date_raw);assert.ok(x.date_precision);}
assert.deepEqual(await call('/api/collections',undefined,randomUUID().replace(/-/g,'')),[]);const isolated=await fetch(site+'/api/collections/'+c.id,{headers:{...headers,'x-videoscope-workspace':randomUUID().replace(/-/g,'')}});assert.equal(isolated.status,404);
const browser=await chromium.launch(),ctx=await browser.newContext({viewport:{width:390,height:844}});await ctx.addInitScript(t=>localStorage.setItem('videoscope-workspace-v33',JSON.stringify(t)),token);const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
// Metadata is tested against real records. Media bodies are not copied to logs or screenshots.
await page.route('**/*',route=>route.request().resourceType()==='image'?route.abort():route.continue());await page.goto(site);await page.waitForSelector('.recent-item',{state:'attached'});await page.evaluate(()=>document.querySelector('.recent-item').click());await page.waitForFunction(n=>document.querySelector('#statVideos').textContent===String(n),c.items.length);assert.equal(await page.locator('.video-card').count(),Math.min(c.items.length,24));assert.equal(await page.locator('.card-title').first().textContent(),[...c.items].sort((a,b)=>b.views-a.views)[0].title);await page.click('#themeButton');assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.locator('[data-detail]').first().click();assert.ok(await page.locator('#detailDialog').isVisible());await page.click('[data-close="detailDialog"]');await page.locator('[data-save]').first().click();await page.click('#mobileSaved');assert.equal(await page.locator('.video-card').count(),1);assert.deepEqual(errors,[]);await browser.close();
const imageCheck=await fetch(c.items[0].thumbnail_url,{method:'HEAD',signal:AbortSignal.timeout(10000)}).then(r=>({status:r.status,type:r.headers.get('content-type')})).catch(e=>({error:e.message}));
const report={site,tested_at:new Date().toISOString(),version:'3.3.0',pages:job.pages,source_reported:job.expected,unique_videos:c.items.length,original_titles:c.items.filter(x=>!!x.title).length,original_thumbnails:c.items.filter(x=>!!x.thumbnail_url).length,views:c.items.filter(x=>typeof x.views==='number').length,ratings:c.items.filter(x=>typeof x.rating==='number').length,source_dates:c.items.filter(x=>!!x.date_raw).length,precise_dates:c.items.filter(x=>['day','timestamp'].includes(x.date_precision)).length,detail_pages_read:job.details_checked,detail_failures:job.details_failed,with_source_files:c.items.filter(x=>x.source_files?.length).length,with_public_comments:c.items.filter(x=>x.comments?.length).length,thumbnail_probe:imageCheck,workspace_isolation:true,live_mobile_controls:true};
await mkdir('artifacts',{recursive:true});await writeFile('artifacts/hosted-verification.json',JSON.stringify(report,null,2));console.log('HOSTED_VERIFICATION_PASSED',JSON.stringify(report));
// Remove only collections created by this test token, never user data.
await fetch(site+'/api/collections/'+c.id,{method:'DELETE',headers});
