import assert from 'node:assert/strict';
import * as cheerio from 'cheerio';
import {readPublic,readRobots,allowedByRobots} from '../lib/network.mjs';
import {parseListing,parseDetail,clean} from '../lib/extract.mjs';
const base='https://www.tokyomotion.net/user/yua_xx/videos',rules=await readRobots(base);assert.ok(allowedByRobots(rules,base));const ids=new Set();let next=base,pages=0,expected=null,matched=0,example=null;
while(next&&pages<10){
 const fetched=await readPublic(next),parsed=parseListing(fetched.html,fetched.url),$=cheerio.load(fetched.html),roots=$('[id^="video_"]').filter((_,n)=>/^video_\d+$/.test($(n).attr('id')||''));assert.equal(parsed.items.length,roots.length);if(expected===null)expected=parsed.expected;
 for(const item of parsed.items){const id=new URL(item.url).pathname.match(/^\/video\/(\d+)/)?.[1];assert.ok(id);const root=$('#video_'+id),a=root.find('a').first();const originalTitle=clean(a.attr('title')||root.children('a').last().text()||root.find('img').attr('alt'));assert.ok(item.title===originalTitle,'Original title mismatch at video '+id);assert.ok(item.thumbnail_url===new URL(root.find('img').first().attr('src'),base).href,'Source thumbnail mismatch at video '+id);assert.equal(item.views,Number(root.find('.video-views').text().match(/[\d,]+/)[0].replace(/,/g,'')));assert.ok(item.date_raw===clean(root.find('.video-added').text()));assert.ok(item.duration_seconds>0);const originalRating=root.find('.video-rating').hasClass('no-rating')?null:Number(root.find('.video-rating b').text().replace('%','').trim());assert.equal(item.rating,originalRating);assert.ok(!/^(EN|Login|More|Favorite Videos)$/.test(item.title));assert.ok(!ids.has(item.id),'Pagination returned duplicate video');ids.add(item.id);matched++;if(!example)example=item}
 pages++;console.log(JSON.stringify({page:pages,video_count:parsed.items.length,all_original_fields_matched:parsed.items.length,source_total:parsed.expected}));next=parsed.next;await new Promise(r=>setTimeout(r,350));
}
assert.equal(ids.size,expected);assert.equal(next,null);console.log('VERIFIED_PUBLIC_LIST',JSON.stringify({pages,unique_videos:ids.size,source_total:expected,all_original_fields_matched:matched}));
const detail=await readPublic(example.url),d=parseDetail(detail.html,detail.url,example);assert.equal(d.is_video,true);assert.ok(d.title&&d.thumbnail_url);assert.ok(d.duration_seconds>0);console.log('VERIFIED_DETAIL',JSON.stringify({title_present:!!d.title,thumbnail_present:!!d.thumbnail_url,duration_present:!!d.duration_seconds,date_precision:d.date_precision,tags:d.tags.length,public_comments:d.comments.length,source_files:d.source_files.length,source_download_buttons:d.download_links.length}));
const value=detail.html.match(/var\s+video_add\s*=\s*([^;]+);/)?.[1]||'';console.log('DATE_SOURCE_HINT',/^\s*["']?\d{8,13}["']?\s*$/.test(value)?value:'not a numeric timestamp');
let otherPassed=false;for(const url of ['https://www.w3.org/2010/05/video/mediaevents.html','https://www.w3schools.com/html/html5_video.asp']){try{const page=await readPublic(url),v=parseDetail(page.html,page.url);assert.equal(v.is_video,true);console.log('VERIFIED_OTHER_SOURCE',JSON.stringify({url,video_detected:v.is_video,title_present:!!v.title,source_files:v.source_files.length}));otherPassed=true;break}catch(e){console.log('OTHER_SOURCE_UNAVAILABLE',JSON.stringify({url,message:e.message}))}}assert.ok(otherPassed,'At least one additional public video page must be tested');
