import assert from 'node:assert/strict';
import * as cheerio from 'cheerio';
import {readPublic,readRobots,allowedByRobots} from '../lib/network.mjs';
import {parseListing,parseDetail} from '../lib/extract.mjs';
const base='https://www.tokyomotion.net/user/yua_xx/videos',rules=await readRobots(base);assert.ok(allowedByRobots(rules,base));const ids=new Set();let next=base,pages=0,expected=null,matched=0;let example=null;
while(next&&pages<10){const fetched=await readPublic(next),parsed=parseListing(fetched.html,fetched.url),$=cheerio.load(fetched.html),roots=$('[id^="video_"]').filter((_,n)=>/^video_\d+$/.test($(n).attr('id')||''));assert.equal(parsed.items.length,roots.length);if(expected===null)expected=parsed.expected;for(const item of parsed.items){const id=new URL(item.url).pathname.match(/^\/video\/(\d+)/)?.[1];assert.ok(id);const card=$('#video_'+id),a=card.find('a[title]').first();assert.equal(item.title,a.attr('title').replace(/\s+/g,' ').trim());assert.equal(item.thumbnail_url,new URL(card.find('img').first().attr('src'),base).href);assert.equal(item.views,Number(card.find('.video-views').text().match(/[\d,]+/)[0].replace(/,/g,'')));assert.equal(item.date_raw,card.find('.video-added').text().replace(/\s+/g,' ').trim());assert.ok(item.duration_seconds>0);assert.ok(item.rating===null||(item.rating>=0&&item.rating<=100));assert.ok(!/^(EN|Login|More|Favorite Videos)$/.test(item.title));assert.ok(!ids.has(item.id),'Pagination returned duplicate video');ids.add(item.id);matched++;if(!example)example=item}pages++;console.log(JSON.stringify({page:pages,video_count:parsed.items.length,matched_title_thumbnail_views_date:parsed.items.length,source_total:parsed.expected}));next=parsed.next;await new Promise(r=>setTimeout(r,350))}
assert.equal(ids.size,expected);assert.equal(next,null);console.log('VERIFIED_PUBLIC_LIST',JSON.stringify({pages,unique_videos:ids.size,source_total:expected,all_original_fields_matched:matched}));
const detail=await readPublic(example.url),d=parseDetail(detail.html,detail.url,example);assert.equal(d.is_video,true);assert.ok(d.title&&d.thumbnail_url);assert.ok(d.duration_seconds>0);console.log('VERIFIED_DETAIL',JSON.stringify({title_present:!!d.title,thumbnail_present:!!d.thumbnail_url,duration_present:!!d.duration_seconds,date_precision:d.date_precision,tags:d.tags.length,public_comments:d.comments.length,source_files:d.source_files.length,source_download_buttons:d.download_links.length}));
const doc=cheerio.load(detail.html);console.log('DATE_SOURCE_VALUE',detail.html.match(/var\s+video_add\s*=\s*[^;]+;/)?.[0]?.slice(0,250)||'none');
for(const url of ['https://www.w3.org/2010/05/video/mediaevents.html','https://www.w3schools.com/html/html5_video.asp']){try{const page=await readPublic(url),v=parseDetail(page.html,page.url);assert.equal(v.is_video,true);console.log('VERIFIED_OTHER_SOURCE',JSON.stringify({url,video_detected:v.is_video,title_present:!!v.title,source_files:v.source_files.length}));break}catch(e){console.log('OTHER_SOURCE_UNAVAILABLE',JSON.stringify({url,message:e.message}))}}
